### ISSUE TITLE
[question] directly query metadata

### ISSUE THREAD

**Issue by jkiebzak** [rozofs/rozofs#103]
We need a way to query the metadata file dates - atime, ctime, mtime. Instead of crawling the file tree, is there a way to hook into the metadata and query the meta directly? we currently have 10's of millions of files, and will be expanding to hundreds of millions of files - thus walking the directory tree would be too expensive.

**Comment by rozodopamine** [comment]
Hi Jason,
the master release under github is the release 1 of our product.
In release 2 of RozoFS we have done lots of improvements related to the meta data,
in order to make file indexing faster. We have a rozo_find utility with the same syntax
and semantic as the usual Linux find that provides fast query on the system when the 
Linux find is not usable any more (too slow).
We are currently in the process to decide whether this utility will be part of the open source
project, or whether we will only provide it to our licenced customer.

As an example:

Making the list of all files in the system: (./rozo_find /srv/rozofs/exports/export_1 -name "*" > tout)
takes 635 ms for 422506 files

Searching for the files modified 4 days ago ( ./rozo_find /srv/rozofs/exports/export_1 -mtime 4 > 4jours)
takes 28,3 ms to build a list of 3125 files among the existing 422506 in the system.

Looking for files bigger than 1GB (./rozo_find /srv/rozofs/exports/export_1 -size +1G > gros)
takes 285 ms to find out the 4 files within the 422506 in the system that are bigger than 1GB. 

Regarding the security, the communication between the nodes is done on rpc above TCP/IP and is 
not secured. Nevertheless the data sent from our client toward the servers are not clear user data, but 
data transformed thanks to our FEC (the mojette transform). We have also an encryption method that is 
only experimental for the moment, where we apply the encryption/decryption only on few pieces of 
the data after/before our FEC. It is fast since encryption is only applied on some bytes, but combined
with our FEC it provides strong confidentiality.

Regards,
JPierre
