### ISSUE TITLE
rozofs opensource future?

### ISSUE THREAD

**Issue by junewinter2013** [rozofs/rozofs#107]
Beside the small commits done on 24-Jul-15, there has not been any commit since 17-Nov-14.

With the expansion into the USA:
http://blog.rozosystems.com//news/2015/10/05/rozo-systems-opens-US-headquarters-in-silicon-valley/

Will the opensource version of rozofs be continually developed ?

**Comment by rozonicotine** [comment]
Hello,

The fact that there is an expansion in USA does not change the fact that
RozoFS will remain open source. Your comments
are related to the Master branch of RozoFS that is now under maintenance,
and the one that we currently deploy on production
sites, since May 2015,  is the one under feature/mdevice.

Best Regards,

Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs


2015-10-22 3:21 GMT+02:00 junewinter2013 <notifications@github.com>:

> Beside the small commits done on 24-Jul-15, there has not been any commit
> since 17-Nov-14.
>
> With the expansion into the USA:
>
> http://blog.rozosystems.com//news/2015/10/05/rozo-systems-opens-US-headquarters-in-silicon-valley/
>
> Will the opensource version of rozofs be continually developed ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/107>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by junewinter2013** [comment]
Thanks for the quick reply.
I should have checked all the branches before asking the question :(
We shall start playing with rozofs using the "feature/mdevice" branch.
