### ISSUE TITLE
rozofs layouts

### ISSUE THREAD

**Issue by junewinter2013** [rozofs/rozofs#108]
The rozofs layouts are defined by a tuple (m,n,s), currenty the defaults only support a maximum of (8, 12, 16).

1. How big can those numbers be? Can s = 256?
2. How easy it is to change the layout for existing data? Can it be performed on the fly while rozofs is being mounted and used?

**Comment by rozonicotine** [comment]
Hi,
Currently, RozoFS provides 3 layouts:

*layout 0:*
the layout 0 can be seen as a RAID-5.
4 servers are allocated for storing projections associated with a file
(result of the erasure coding)
3 are used for writing among the 4 (RozoFS grants a write once data and its
associated redundancy are flushed on disks)
2 among 3 are needed for rebuilding the initial data

*layout 1:*
 The layout 1 can be seen as a RAID-6. and is equivalent to 3 copies when
compared to replica
  8 storage servers are allocated at file creation
  6 are needed for writing
  4 among 6 are needed fro reading

*layout 2:*
  The layout 2 is equivalent to 5 copies when compared to replica
  16 storage servers are allocated at file creation
  12 are needed for writing
  8 among 12 are needed for writing

From a configuration standpoint, to achieve high availability, the minimal
number of storage servers
is 4 for layout 0, 8 for layout 1 and 16 for layout 2.  The storage system
might have more storage
servers that the mininal value required for each of the layout.
So if I refer to your mail, if RozoFS handles 256 storage servers, as
example, for the case of a layout 1
it will select 8 servers among the 256 for storing projections related to
the file.

However, on a storage node, it might be possible that the file will be
stored on more that one disk depending
on how the disks have been organized (i.e: usage of RAID 0) and also
according to the total file size since
on the storage nodes a projections of a file has a max size of 64 GB and
can have up to 128 chunks.


The allocation of the set of storage servers is done at file creation time,
and remains unchanged for
the file until it is deleted.
The allocation of a set of servers can be achieved:

   - according to the remaining space of each server
   -  in a round-robin way (typically the one that we are using for
   cloud-DVR
   -  in a weighed round-robin way

The layout is a parameter associated with a filesystem and can not be
changed on the fly.

Best Regards,

Didier Féron

2015-10-23 6:11 GMT+02:00 junewinter2013 <notifications@github.com>:

> The rozofs layouts are defined by a tuple (m,n,s), currenty the defaults
> only support a maximum of (8, 12, 16).
>
>    1. How big can those numbers be? Can s = 256?
>    2. How easy it is to change the layout for existing data? Can it be
>    performed on the fly while rozofs is being mounted and used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/108>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by truatpasteurdotfr** [comment]
just to clear a possible confusion: "a projection of a file has a max size of 64 GB and can have up to 128 chunks" does that mean that the maximum storage occupied by a projection on a given storage node is: 64 GBx 128= 8TB ? then the maximum file size of a layout 0 is 2x 8TB, layout 1 is 4x 8TB and layout 2 is 8x 8TB ?

**Comment by rozodopamine** [comment]
Hi Tru Huynh,
a file is divided by RozoFS in chunks of 64GB. The maximum number of chunks
for a file is 128.
One can so write a maximum of 128x64GB of data in a file. In other words
the maximum file size
is 8TB whatever the layout.

The size of a chunk of user data is 64 GiB. The size of a projection chunk
depends on the layout:

Layout

Storage chunk size

128 chunks sum

0

32 GiB

4 TiB

1

16 GiB

2 TiB

2

8 GiB

1 TiB

The bigger is the layout, the smaller is the projection, and so the smaller
is the chunk file on
the storage.
Regards,
JPierre


2015-10-26 16:18 GMT+01:00 Tru Huynh <notifications@github.com>:

> just to clear a possible confusion: "a projection of a file has a max size
> of 64 GB and can have up to 128 chunks" does that mean that the maximum
> storage occupied by a projection on a given storage node is: 64 GBx 128=
> 8TB ? then the maximum file size of a layout 0 is 2x 8TB, layout 1 is 4x
> 8TB and layout 2 is 8x 8TB ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/108#issuecomment-151170720>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*
