### ISSUE TITLE
rozofs/2.0.~alpha84-1.el6.x86_64 storcli[22446]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error

### ISSUE THREAD

**Issue by truatpasteurdotfr** [rozofs/rozofs#113]
1 client rsync -> /mnt/rozofs (testing rsync)
client side:
```
[tru@c-esxi centos]$ rsync -aPHSv tlalac.erc::centos/6.7 .
...
rsync: write failed on "/mnt/rozofs/var/ftp/pub/centos/6.7/centosplus/x86_64/Packages/kernel-2.6.32-573.3.1.el6.centos.plus.x86_64.rpm": Input/output error (5)

client logs:
Dec 18 11:40:24 c-esxi storcli[913]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error
Dec 18 12:11:40 c-esxi storcli[913]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error
```
1 exportd, 2x 8 storaged (single disk):
exportd log (which is also the rsync server):
```
Dec 18 12:11:03 mfsmaster-eth1 xinetd[7135]: START: rsync pid=2563 from=::ffff:10.11.3.100
Dec 18 12:11:40 mfsmaster-eth1 xinetd[7135]: EXIT: rsync status=12 pid=2563 duration=37(sec)
Dec 18 12:12:48 mfsmaster-eth1 storcli[22446]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error
Dec 18 12:12:48 mfsmaster-eth1 storcli[22446]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error
Dec 18 12:12:48 mfsmaster-eth1 storcli[22446]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error
Dec 18 12:13:13 mfsmaster-eth1 storcli[22446]: rozofs_storcli_write.c - 2047 - severe: FDL read internal error Input/output error
```
/etc/rozofs/export.conf
```
layout = 1 ;

volumes = # List of volumes
(   
    {   
        # First volume
        vid = 1 ; # Volume identifier = 1
        cids=     # List of clusters for the volume 1
        (   
            {   
                # First cluster of volume 1
                cid = 1;  # Cluster identifier = 1
                sids =    # List of storages for the cluster 1
                (
                        {sid =  1; host = "c001.erc";},
                        {sid =  2; host = "c002.erc";},
                        {sid =  3; host = "c003.erc";},
                        {sid =  4; host = "c004.erc";},
                        {sid =  5; host = "c005.erc";},
                        {sid =  6; host = "c006.erc";},
                        {sid =  7; host = "c007.erc";},
                        {sid =  8; host = "c008.erc";}
                );
            },
            {   
                # Second cluster of volume 1
                cid = 2;  # Cluster identifier = 2
                sids =    # List of storages for the cluster 2
                (
                        {sid =  1; host = "c009.erc";},
                        {sid =  2; host = "c010.erc";},
                        {sid =  3; host = "c011.erc";},
                        {sid =  4; host = "c012.erc";},
                        {sid =  5; host = "c013.erc";},
                        {sid =  6; host = "c014.erc";},
                        {sid =  7; host = "c015.erc";},
                        {sid =  8; host = "c016.erc";}
                );
            }
        );
    }
);




exports = ( # List of exported filesystem

    # First filesystem exported
    {eid = 1; root = "/rozofs/one"; bsize="4K";  md5="";
                                     squota=""; hquota="";vid=1;}

);
```
storage.conf: (cid/sid changed on the 15 other storaged)
```
[tru@c001 ~]$ cat /etc/rozofs/storage.conf
listen = (
   {
      addr = "*";
      port = 41001;
   }
);

storages = (
  {cid = 1; sid = 1; root = "/srv/storage/c1_s1"; device-total = 1; device-mapper = 1; device-redundancy = 1;}
);
```
/etc/fstab (storaged) single 500GB sata disk
```
/dev/sda /srv/storage/c1_s1/0 xfs rw,relatime,attr2,inode64,noquota 0 0
```

**Comment by truatpasteurdotfr** [comment]
trying on CentOS-7 client/servers/exportd ie not the same setup (layout=0 4x storaged (2 disks each)), no issue.

**Comment by truatpasteurdotfr** [comment]
I tried to scale down to 1 cluster -> same issue, rsync starts fine but fails after a while.

The client node idle (before starting the rsync) has a load of 5 with 100% cpu_idle. Not idea if it is related or not.

**Comment by rozodopamine** [comment]
Hi Tru Huynh,
it looks like a problem that we have recently fixed in 2.0.alpha81 related
 to crc32 generation.
In some special cases a bad CRC32 was generated. If you are rsyncing toward
a RozoFS older than 2.0.alpha81,
or if the files you are rsyncing have been written on a RozoFS older than
2.0.alpha81 you may experience false
CRC32 error detection.
Can you please provide us with the output of the command on the RozoFS
mount point where the problem occurs.
rozodiag -T mount:0 -T mount:0:1 -T mount:0:2 -c version -c profiler
If some read_blk_crc are displayed this is the problem.
To fix the problem, get the latest version of RozoFS.
If you need to re-read the files that you have saved with the older
version, just disable CRC32 control by setting the line
crc32c_check = False;
in the files /etc/rozofs/rozofs.conf (or /usr/local/etc/rozofs/rozofs.conf)
on every storage node and restart the storaged.
I hope this can help.
Regards,
JPierre



2015-12-18 17:23 GMT+01:00 Tru Huynh <notifications@github.com>:

> I tried to scale down to 1 cluster -> same issue, rsync starts fine but
> fails after a while.
>
> The client node idle (before starting the rsync) has a load of 5 with 100%
> cpu_idle. Not idea if it is related or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/113#issuecomment-165824537>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by truatpasteurdotfr** [comment]
sorry for the delay, it was a clean install, not a upgrade. I will tray with the latest version and report :D

**Comment by truatpasteurdotfr** [comment]
no more issue on later version :P
