### ISSUE TITLE
exportd goes SIGABRT with "severe: can't initialize export with path <path>: Operation not supported"

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#114]
I updated to the latest alpha (building from `feature/mdevice`) and now I can't start exportd anymore. 

```
Dec 22 09:46:28 tsubame exportd[4122]: exportd.c - 1194 - info: initializing export 1 path /srv/rozofs/exports/export_1
Dec 22 09:46:28 tsubame exportd[4122]: export_track_change.c - 492 - info: inode export tracking thread started 
Dec 22 09:46:28 tsubame exportd[4122]: dirent_writeback_cache.c - 362 - info: WriteBack cache thread started 
Dec 22 09:46:28 tsubame exportd[4122]: export_tracking.c - 1170 - severe: open failure for /srv/rozofs/exports/export_1/0/00000000-0000-4000-0000-000000000030 : Operation not supported
Dec 22 09:46:28 tsubame exportd[4122]: exportd.c - 1201 - severe: can't initialize export with path /srv/rozofs/exports/export_1: Operation not supported
Dec 22 09:46:28 tsubame exportd[4122]: exportd.c - 1258 - fatal: can't load exports
Dec 22 09:46:28 tsubame exportd[4122]: rozofs_core_files.c - 270 - info: Receive signal 6 = SIGABRT
```

Export configuration is available at: https://gist.github.com/lbeltrame/1ec6ae569029590cf625

**Comment by lbeltrame** [comment]
This occurred only on 3 of the 4 nodes which make up the RozoFS filesystem layout, but of course (Murphy's law!) this is the export hostname, so filesystems can't be mounted unless I figure out what's going on...

**Comment by rozodopamine** [comment]
Hi Luca,
a new feature has been introduced for test in alpha72 that introduced a
bug. This bug has
been fixed in alpha76.  Since we had no licenced customer that was
installed with a release
within  [72:76] we felt free to make a fix that render this version
interval incompatible with the
other releases (comprising the latest one that you have taken).
From what we see, you were unfortunately running one of these [72:76]
versions which is not
compatible with the new one you have taken. We could build for you a
specific line of product
keeping the compatibility with your initial release, but since you the only
unfortunate guy running
these bad versions, since you are not yet a licenced customer and
considering that you are not
in production but only in tests, we would prefer that you re-install your
RozoFS system from
scratch with the latest version if you do not mind.
We feel very sorry for the inconvenience,
JPierre


2015-12-22 9:50 GMT+01:00 Luca Beltrame <notifications@github.com>:

> I updated to the latest beta (building from feature/mdevice) and now I
> can't start exportd anymore.
>
> Dec 22 09:46:28 tsubame exportd[4122]: exportd.c - 1194 - info: initializing export 1 path /srv/rozofs/exports/export_1
> Dec 22 09:46:28 tsubame exportd[4122]: export_track_change.c - 492 - info: inode export tracking thread started
> Dec 22 09:46:28 tsubame exportd[4122]: dirent_writeback_cache.c - 362 - info: WriteBack cache thread started
> Dec 22 09:46:28 tsubame exportd[4122]: export_tracking.c - 1170 - severe: open failure for /srv/rozofs/exports/export_1/0/00000000-0000-4000-0000-000000000030 : Operation not supported
> Dec 22 09:46:28 tsubame exportd[4122]: exportd.c - 1201 - severe: can't initialize export with path /srv/rozofs/exports/export_1: Operation not supported
> Dec 22 09:46:28 tsubame exportd[4122]: exportd.c - 1258 - fatal: can't load exports
> Dec 22 09:46:28 tsubame exportd[4122]: rozofs_core_files.c - 270 - info: Receive signal 6 = SIGABRT
>
> Export configuration is available at:
> https://gist.github.com/lbeltrame/1ec6ae569029590cf625
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/114>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by lbeltrame** [comment]
Thanks, I'll rebuild the exports from scratch. I'll close this report, as it's obviously invalid.
