### ISSUE TITLE
[Debian / Ubuntu packaging] Package update of rozofsmount unmounts volumes

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#141]
The operation can be potentially disruptive for RozoFS volumes that are exported to other hosts not using RozoFS (e.g., a data store exported via NFS). 

Unmounting a file system during package upgrade should never be done, it violates the principle of least surprise.

**Comment by lbeltrame** [comment]
As this broke a backup script (because it tried to unmount things while it was running) resulting in **data loss**, this should at least get looked at.

**Comment by rozoadrenaline** [comment]
This is fixed since version 2.1.15. see: ebf836b.

**WARNING**:
If you upgrade rozofs-rozofsmount package from version 2.1.14 (or earlier) to version 2.1.15 (or later): RozoFS mountpoints will be automatically unmounted (if not used) but NOT AUTOMATICALLY MOUNTED after.

You can disable init script before the upgrade with this command:
```
chmod a-x /etc/init.d/rozofs-rozofsmount
```

**Comment by lbeltrame** [comment]
Seems to work. Thanks.
