### ISSUE TITLE
Data integrity checking -- please implement

### ISSUE THREAD

**Issue by onlyjob** [rozofs/rozofs#89]
I just reproduced silent data corruption (no errors whatsoever) with unreliable HDD used as one of five storage devices (layout=0).

Data integrity checking is crucial for reliable storage system.

**Comment by truatpasteurdotfr** [comment]
what about using zfs as backend storage instead? with one single copy, you can hopefully say if the chunk read is ok, and choose to use more space (>=2 copies) to ensure that you get a "good" read.

**Comment by rozonicotine** [comment]
Hi,

Thanks for the suggestion, but we have already introduced the integrity
checking and self healing capability on our mutli-dev feature branch.
Each projection block is protected by a CRC32_C (2K,4K depending on the
layout). In case of CRC error, the client keeps track of the projection
(block) in error and once the initial filesystem block has been rebuild,
RozoFS re-generates the projection for which a CRC error has been reported.
Then that projection is sent back to the storage for re-writing.

Using erasure coding requires less storage room than the one proposed by
ZFS that relies on RAId 1.
(twice the space).

Best Regards,

Didier

2015-03-24 18:38 GMT+01:00 Tru Huynh <notifications@github.com>:

> what about using zfs as backend storage instead? with one single copy, you
> can hopefully say if the chunk read is ok, and choose to use more space
> (>=2 copies) to ensure that you get a "good" read.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/89#issuecomment-85612704>.
>



-- 

Didier Féron

CTO -06.47.93.08.95

didier.feron@rozofs.com

www.rozofs.com

https://github.com/rozofs/rozofs

**Comment by onlyjob** [comment]
@rozonicotine that's great news. With properly implemented integrity checking RozoFS can become first viable erasure-coded storage solution (Ceph is totally worthless due to gross disregard to data integrity).
How is error reporting implemented? 
Is there a way to identify problematic node without logging into it? A problematic HDD on the node?
Is there background scrubbing (a must-have feature)?  
Please remember that re-writing to the same HDD may not be possible - sometimes HDDs manifest errors when most of the data can be read but not necessary re-written.

@truatpasteurdotfr, built-in integrity checking is a must because HDD is not the only place where data may get corrupted. ZFS may significantly increase RAM requirements for RozoFS nodes. I tried to use Btrfs with storage systems without integrity checking (a sloppy and incomplete workaround for lack of integrity checking) but Btrfs can not accurately report remaining free space on near-full partitions. ZFS may have similar problem. Besides COW file systems are generally slower...

**Comment by rozonicotine** [comment]
Hi,

Concerning the error reporting, we avoid to rely on syslog because this can
hurt the system. There is a specific counter for that kind of error. Then
we rely on some script that can poll rozoFS and raise an alarm when a
configured threshold is reached (Typically we have scripts embedded with
Nagios for that purpose).
Notice that the error is reported on the client and on the storage node
that encounters the issue.

Faulty node identification:
In RozoFS, we use a sid (storage identifier) for identifying a logical disk
that is located on a specific node. So with the sid
we identify the storage node and then within the storage node the local
filesystem associated with the sid.
Now the issue is about the source of the error: it could be the HDD and
something wrong on filesystem mounted on that HDD(s). If at the time we
attempt to re-write to the disk the system encounters an error in that case
that SID is set out of service. The tricky thing is to find out what is a
permanent error (failed HDD) or an ephemeral error. Also in terms of
permanent error we must also considered a corrupted filesystem. From a
RozoFS standpoint it does not make a big difference: the SID is set out of
service.

COW:
For the storage node we are currently using XFS. I think we will not go to
ZFS because of the penalty introduced by the COW. We might re-consider it
for SSD because we have not the seek penalty that we have with the seek
access of the HDD.


background srcubbing:
The feature is no yet there. However just to give a glance of how we see it
on RozoFS:
  It will take place on the storage node only: The reason for that is to
avoid wasting network bandwidth when there is no reading error.
  In case of error, the storage node that has detected the error will
contact the other storage nodes that contain the associated projections.
Once the initial block has been rebuilt from the projections got from the
other nodes, the storage node regenerate the projection for which the CRC
error has been detected and attempts to re-write it. In case of failure
(because of permanent HDD error), the projection is written on a spare node
in order to keep the same level of redundancy.

If you wish we can contact me on my e-mail : didier.feron@rozofs.com I can
provide you with some documentation about the architecture of RozoFS that
could make the things easier to understand.

Best Regards

Didier




2015-03-24 23:05 GMT+01:00 Dmitry Smirnov <notifications@github.com>:

> @rozonicotine <https://github.com/rozonicotine> that's great news. With
> properly implemented integrity checking RozoFS can become first viable
> erasure-coded storage solution (Ceph is totally worthless due to gross
> disregard to data integrity).
> How is error reporting implemented?
> Is there a way to identify problematic node without logging into it? A
> problematic HDD on the node?
> Is there background scrubbing (a must-have feature)?
>
> Please remember that re-writing to the same HDD may not be possible -
> sometimes HDDs manifest errors when most of the data can be read but not
> necessary re-written.
>
> @truatpasteurdotfr <https://github.com/truatpasteurdotfr>, built-in
> integrity checking is a must because HDD is not the only place where data
> may get corrupted. ZFS may significantly increase RAM requirements for
> RozoFS nodes. I tried to use Btrfs with storage systems without integrity
> checking (a sloppy and incomplete workaround for lack of integrity
> checking) but Btrfs can not accurately report remaining free space on
> near-full partitions. ZFS may have similar problem. Besides COW file
> systems are generally slower...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/89#issuecomment-85711533>.
>



-- 

Didier Féron

CTO -06.47.93.08.95

didier.feron@rozofs.com

www.rozofs.com

https://github.com/rozofs/rozofs

**Comment by rozodopamine** [comment]
Data integrity has been implemented thanks to CRC32 block checking on the storage node, and the rpair procedure from the rozofsmount when some CRC32 error is detected.
